spring:
  application:
    name: service-discovery
  profiles:
    active: default
  config:
    import: ${SPRING_CONFIG_IMPORT}

management:
  endpoints:
    web:
      exposure:
        include: "*"